service: next-js-dynamodb-project
frameworkVersion: "3"

custom:
  tableName: "taksmate-table-${sls:stage}"

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [MainTable, Arn]
  environment:
    DYNAMO_TABLE: ${self:custom.tableName}

functions:
  app:
    handler: lambda.handler
    memorySize: 256
    events:
      - http:
          method: ANY
          path: /
          contentHandling: CONVERT_TO_BINARY
      - http:
          method: ANY
          path: "{proxy+}"
          contentHandling: CONVERT_TO_BINARY

resources:
  Resources:
    MainTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
          - AttributeName: taskStatus
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
          - AttributeName: updatedAt
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: TasksBySK
            KeySchema:
              - AttributeName: SK
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: TasksByUserAndUpdatedAt
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: updatedAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: TasksByUserAndStatus
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: taskStatus
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        DeletionPolicy: Retain
